---

language: python
python: 2.7

sudo: required

# Enable the docker service
services:
  - docker

# Install molecule and docker-py
install:
  - pip install -r test-requirements.txt

# Test all the scenarios
script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
