---

- block:

  - name: Ensure the override directory exists (systemd)
    file:
      name: "/etc/systemd/system/{{ pdns_service_name }}.service.d"
      state: directory
      owner: "{{ pdns_fileowner.user }}"
      group: "{{ pdns_fileowner.group }}"

  - name: Override the PowerDNS Authoritative Server unit (systemd)
    template:
      src: "override-service.systemd.conf.j2"
      dest: "/etc/systemd/system/{{ pdns_service_name }}.service.d/override.conf"
      owner: "{{ pdns_fileowner.user }}"
      group: "{{ pdns_fileowner.group }}"
    notify: reload systemd and restart PowerDNS

  when: pdns_service_overrides != {}
    and ansible_service_mgr == "systemd"

- name: Ensure that the PowerDNS Authoritative Server configuration directory exists
  file:
    name: "{{ pdns_config_dir }}"
    state: directory
    owner: "{{ pdns_fileowner.user }}"
    group: "{{ pdns_fileowner.group }}"
    mode: 0750

- name: Generate the PowerDNS Authoritative Server configuration
  template:
    src: pdns.conf.j2
    dest: "{{ pdns_config_dir }}/{{ pdns_config_file }}"
    owner: "{{ pdns_fileowner.user }}"
    group: "{{ pdns_fileowner.group }}"
    mode: 0640
  notify: restart PowerDNS

- name: Ensure that the PowerDNS Authoritative Server 'include-dir' directory exists
  file:
    name: "{{ pdns_config['include-dir'] }}"
    state: directory
    owner: "{{ pdns_fileowner.user }}"
    group: "{{ pdns_fileowner.group }}"
    mode: 0750
  when: "pdns_config['include-dir'] is defined"
