---

- name: Ensure the PowerDNS Authoritative Server configuration directory exists
  file:
    name: "{{ pdns_config_dir }}"
    state: directory
    owner: "root"
    group: "root"
    mode: 0755

- name: Generate the PowerDNS Authoritative Server configuration
  template:
    src: pdns.conf.j2
    dest: "{{ pdns_config_dir }}/{{ pdns_config_file }}"
    owner: "root"
    group: "root"
    mode: 0640
  notify: Restart PowerDNS

- name: Ensure that the PowerDNS Authoritative Server include-dir configuration directory exists
  file:
    name: "{{ pdns_config['include-dir'] }}"
    state: directory
    owner: "root"
    group: "root"
    mode: 0755
  when: "pdns_config['include-dir'] is defined"
