---
- name: Check pdns_repo_provider
  fail: msg="pdns_repo_provider is neither 'powerdns' nor 'os'"
  when: pdns_repo_provider not in ["os", "powerdns"]

# XXX: Is this handy to check ( I guess... no)
- name: Check pdns_repo_branch
  fail: msg="pdns_repo_branch isn't set to a known branch"
  when: pdns_repo_provider == "powerdns" and pdns_repo_branch not in ["master"]

- name: Add the PowerDNS repository key
  apt_key: url=http://repo.powerdns.com/CBC8B383-pub.asc id=D47975F8DAE32700A563E64FFF389421CBC8B383
  when: pdns_repo_provider == "powerdns" and pdns_repo_branch == "master"

- name: apt-pin the PowerDNS packages to the PowerDNS repo
  copy: dest='/etc/apt/preferences.d/pdns' src=pdns.pin owner=root group=root mode=0644
  when: pdns_repo_provider == "powerdns"

# XXX: These repo's don't exist yet
#- name: Add the PowerDNS repository key
#  apt_key: url=http://repo.powerdns.com/FD380FBB-pub.asc id=9FAAA5577E8FCF62093D036C1B0C6205FD380FBB
#  when: pdns_repo_provider == "powerdns" pdns_repo_branch in ["4", "stable"]

- name: Add the PowerDNS repository
  apt_repository: repo="deb http://repo.powerdns.com/{{ansible_distribution | lower}} {{ansible_distribution_release|lower}}-auth-{{pdns_repo_branch}} main"
  when: pdns_repo_provider == "powerdns"

- name: Install the main PowerDNS package
  apt: name=pdns-server state=present

- name: Install module packages
  apt: name=pdns-backend-{{pdns_mapping_launch_deb_backends[item.split('-')[0]] | default(item.split('-')[0])}} state=installed
  with_items: pdns_backends.keys()
  when: item.split(':')[0] != "bind" and item != ""
