---

- name: Install epel-release on CentOS/RedHat
  yum:
    name: epel-release
    state: present
  when: ansible_distribution in [ 'RedHat', 'CentOS' ]

- name: Install epel-release on OracleLinux
  yum:
    name: 'https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm'
    state: present
  when: ansible_distribution in [ 'OracleLinux' ]
