---
- name: Check pdns_repo_provider
  fail:
    msg: "pdns_repo_provider is neither 'powerdns' nor 'os'"
  when: pdns_repo_provider not in ["os", "powerdns"]

- name: Install yum-plugin-priorities
  yum:
    name: yum-plugin-priorities
    state: installed
  when: pdns_repo_provider == "powerdns"

- name: Add PowerDNS repository
  get_url:
    url: https://repo.powerdns.com/repo-files/{{ansible_distribution | lower()}}-auth-{{pdns_repo_branch}}.repo
    dest: /etc/yum.repos.d/powerdns-auth-{{pdns_repo_branch}}.repo
  when: pdns_repo_provider == "powerdns"

- name: Install epel-release
  yum:
    name: epel-release
    update_cache: yes

- name: Install the PowerDNS yum package
  yum:
    name: pdns
    state: installed

# install backend module packages excluding sqlite
- name: Install module package
  yum:
    pkg: "{{ pdns_backends_dict[item.key.split(':')[0]] }}"
    state: installed
  when: pdns_backends_dict[item.key.split(':')[0]] is defined and item.key.split(':')[0] != 'gsqlite3'
  with_dict: "{{ pdns_backends }}"

- name: Install sqlite backend 
  yum:
    pkg: "pdns-backend-sqlite"
    state: installed
  when: pdns_backends_sqlite3_databases is defined 

# query the installed version to be used getting the schema path
- name: Get the sqlite_backend version
  shell: yum list installed pdns-backend-sqlite | grep pdns-backend-sqlite | awk '{print $2}' | cut -d'-' -f1
  register: pdns_sqlite_backend_version
  changed_when: False
