---

- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- include: "repo-{{ ansible_os_family }}.yml"
  when: pdns_install_repo != ""
  tags:
    - install
    - repository

- include: install-epel.yml
  when: ansible_os_family == 'RedHat' and pdns_install_epel
  tags:
    - install

- name: Get the PowerDNS version information from the Package Manager 
  include: "inspect-{{ ansible_os_family }}.yml"
  when: "pdns_rec_package_version == ''"

- name: Append the version to the PowerDNS package name 
  set_fact:
  pdns_package_name: "{{ pdns_package_name }}-{{ pdns_package_version }}"

- name: Install PowerDNS
  package:
    name: "{{ pdns_package_name }}"
    state: present
  tags:
    - install

- name: Install module packages
  package:
    name: "{{ pdns_backends_packages[item.key.split(':')[0]] }}"
    state: installed
  when: pdns_backends_packages[item.key.split(':')[0]] is defined
  with_dict: "{{ pdns_backends }}"
  tags:
    - install

- include: database-mysql.yml
  when: "pdns_mysql_databases_credentials | length > 0"
  tags:
    - db
    - mysql

- include: database-sqlite3.yml
  when: "pdns_sqlite_databases_locations | length > 0"
  tags:
    - db
    - sqlite

- include: configure.yml
  tags:
    - config

- name: Start and enable the PowerDNS service
  service:
    name: "{{ pdns_service_name }}"
    state: started
    enabled: true
  tags:
    - service

- name: Force handlers flush
  meta: flush_handlers
  when: pdns_flush_handlers
