---
- include: install.packages-debian.yml
  when: pdns_installation_type == "packages" and ansible_os_family == "Debian"
  tags:
    - packages
    - install

- include: install.packages-redhat.yml
  when: pdns_installation_type == "packages" and ansible_os_family == "RedHat"
  tags:
    - packages
    - install

# TODO
#- include: install.source-debian.yml
#  when: pdns_installation_type == "source" and ansible_os_family == "Debian"
#  tags:
#    - source
#    - install
#
# TODO
#- include: install.source-redhat.yml
#  when: pdns_installation_type == "source" and ansible_os_family == "RedHat"
#  tags:
#    - source
#    - install

- include: database.yml
  tags:
    - db
    - database

- include: configuration.yml
  tags:
    - conf
    - config
    - configuration

- name: Start and enable the PowerDNS service
  service:
    name: pdns
    state: started
    enabled: true
