---
- name: Allow mysql connect from pdns in selinux
  ansible.posix.seboolean:
    name: pdns_can_network_connect_db
    state: true
    persistent: true
  when: >-
    (pdns_backends | dict2items
    | selectattr('key', 'search', '^g(mysql|pgsql)(:.*)?$')
    | list
    | length) > 0

- name: Allow pdns to bind to udp high ports
  community.general.seport:
    ports: 10000-20000
    proto: udp
    setype: dns_port_t
    state: present
