---
- name: Allow mysql connect from pdns in selinux
  ansible.posix.seboolean:
    name: pdns_can_network_connect_db
    state: yes
    persistent: yes
  when: "'gmysql' in pdns_backends"

- name: Allow pdns to bind to udp high ports
  community.general.seport:
    ports: 10000-20000
    proto: udp
    setype: dns_port_t
    state: present
